In [1]:
import pandas as pd

In [2]:
dataset= pd.read_csv(r"Book1.csv")
dataset.head(5)

              Description Invoice # Item #  Qty Unit Price Discount   Total
0  Invoice 3-456-1 Data 1   3-456-1      1    1      $1.00    $1.00   $0.00
1  Invoice 3-456-1 Data 2   3-456-1      2    2      $2.00    $2.00   $2.00
2  Invoice 3-456-1 Data 3   3-456-1      3    3      $3.00    $3.00   $6.00
3  Invoice 3-456-1 Data 4   3-456-1      4    4      $4.00    $4.00  $12.00
4  Invoice 3-456-1 Data 5   3-456-1      5    5      $5.00    $5.00  $20.00

In [5]:
dataset.isnull().sum()

Description    0
Invoice #      0
Item #         0
Qty            0
Unit Price     0
Discount       0
Total          0
dtype: int64

In [4]:
dataset["Discount"].fillna(dataset["Discount"].mode()[0],inplace=True)

In [7]:
en_data = dataset[["Discount", "Total"]]
en_data

    Discount    Total
0      $1.00    $0.00
1      $2.00    $2.00
2      $3.00    $6.00
3      $4.00   $12.00
4      $5.00   $20.00
..       ...      ...
112   $25.00  $600.00
113    $5.00  $195.00
114    $5.00  $155.00
115    $7.00  $173.00
116    $5.00  $280.00

[117 rows x 2 columns]

In [8]:
pd.get_dummies(en_data)

,Discount_$1.00,Discount_$10.00,Discount_$11.00,Discount_$12.00,Discount_$13.00,Discount_$14.00,Discount_$15.00,Discount_$16.00,Discount_$17.00,Discount_$18.00,...,Total_$455.00,Total_$462.00,Total_$506.00,Total_$552.00,Total_$56.00,Total_$6.00,Total_$600.00,Total_$72.00,Total_$80.00,Total_$90.00
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
113,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
114,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
115,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
116,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 61 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Discount_$1.00   117 non-null    bool
 1   Discount_$10.00  117 non-null    bool
 2   Discount_$11.00  117 non-null    bool
 3   Discount_$12.00  117 non-null    bool
 4   Discount_$13.00  117 non-null    bool
 5   Discount_$14.00  117 non-null    bool
 6   Discount_$15.00  117 non-null    bool
 7   Discount_$16.00  117 non-null    bool
 8   Discount_$17.00  117 non-null    bool
 9   Discount_$18.00  117 non-null    bool
 10  Discount_$19.00  117 non-null    bool
 11  Discount_$2.00   117 non-null    bool
 12  Discount_$20.00  117 non-null    bool
 13  Discount_$21.00  117 non-null    bool
 14  Discount_$22.00  117 non-null    bool
 15  Discount_$23.00  117 non-null    bool
 16  Discount_$24.00  117 non-null    bool
 17  Discount_$25.00  117 non-null    bool
 18  Discount_$3.00   117 non-null    bool
 19  Discount_$4.00   117 non-null    bool
 20  Discount_$5.00   117 non-null    bool
 21  Discount_$6.00   117 non-null    bool
 22  Discount_$7.00   117 non-null    bool
 23  Discount_$8.00   117 non-null    bool
 24  Discount_$9.00   117 non-null    bool
 25  Total_#VALUE!    117 non-null    bool
 26  Total_$0.00      117 non-null    bool
 27  Total_$100.00    117 non-null    bool
 28  Total_$110.00    117 non-null    bool
 29  Total_$12.00     117 non-null    bool
 30  Total_$132.00    117 non-null    bool
 31  Total_$155.00    117 non-null    bool
 32  Total_$156.00    117 non-null    bool
 33  Total_$173.00    117 non-null    bool
 34  Total_$182.00    117 non-null    bool
 35  Total_$195.00    117 non-null    bool
 36  Total_$2.00      117 non-null    bool
 37  Total_$20.00     117 non-null    bool
 38  Total_$210.00    117 non-null    bool
 39  Total_$240.00    117 non-null    bool
 40  Total_$272.00    117 non-null    bool
 41  Total_$280.00    117 non-null    bool
 42  Total_$30.00     117 non-null    bool
 43  Total_$306.00    117 non-null    bool
 44  Total_$32.00     117 non-null    bool
 45  Total_$342.00    117 non-null    bool
 46  Total_$380.00    117 non-null    bool
 47  Total_$40.00     117 non-null    bool
 48  Total_$42.00     117 non-null    bool
 49  Total_$420.00    117 non-null    bool
 50  Total_$44.00     117 non-null    bool
 51  Total_$455.00    117 non-null    bool
 52  Total_$462.00    117 non-null    bool
 53  Total_$506.00    117 non-null    bool
 54  Total_$552.00    117 non-null    bool
 55  Total_$56.00     117 non-null    bool
 56  Total_$6.00      117 non-null    bool
 57  Total_$600.00    117 non-null    bool
 58  Total_$72.00     117 non-null    bool
 59  Total_$80.00     117 non-null    bool
 60  Total_$90.00     117 non-null    bool
dtypes: bool(61)
memory usage: 7.1 KB

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
one = OneHotEncoder()
one.fit_transform(en_data)

<117x61 sparse matrix of type '<class 'numpy.float64'>'
	with 234 stored elements in Compressed Sparse Row format>

In [33]:
one1 = OneHotEncoder(drop="Discount")
ar = one1.fit_transform(en_data).toarray()

InvalidParameterError: The 'drop' parameter of OneHotEncoder must be a str among {'first', 'if_binary'}, an array-like or None. Got 'Discount' instead.

In [34]:

pd.DataFrame(ar,columns=["Unit Price", "Discount"])

ValueError: Shape of passed values is (117, 61), indices imply (117, 2)